name: to practice
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/chekout@v3
            - uses: actions/setup-node@v3
            - run: make setup
            - run: make test
            - run: make lint

